test_texts = [
    "With multiple degrees of freedom, suitable for complex assembly or precision tasks.",
    "Driven by wheels, used for movement on flat ground.",
    "Quadruped design, adapts to uneven terrain, suitable for climbing and movement in complex environments.",
    "Mimicking human structure, suitable for complex interactions and task execution.",
    "Ground-moving robot capable of autonomous movement and performing transportation tasks.",
    "Able to move on flat indoor surfaces.",
    "Able to walk on uneven surfaces.",
    "Suitable for performing tasks in confined spaces.",
    "Robot capable of moving on rugged terrain.",
    "Suitable for fast movement in narrow spaces.",
    "Six degrees of freedom robotic arm with a simplified structural design.",
    "Three degrees of freedom robotic arm, designed for minimalism.",
    "Robotic arm with a large workspace and high flexibility.",
    "Two-wheeled self-balancing robot, able to perform basic material handling tasks.",
    "Wheeled robot suitable for path planning and simple transportation tasks.",
    "Four-degree-of-freedom robotic arm, capable of stacking and assembly.",
    "Highly flexible bionic robot, able to walk on sandy or muddy surfaces.",
    "Simple four-wheeled cart, suitable for basic cargo transportation tasks.",
    "Robot equipped with a multi-degree-of-freedom mechanical arm, suitable for precision assembly or maintenance work.",
    "Robot with self-balancing capability, suitable for fast movement.",
    "Robot capable of fast movement, suitable for completing transportation tasks in a short time.",
    "Robotic arm with rotating joints, suitable for precision tasks.",
    "Robot capable of quickly adapting to environmental changes and switching tasks.",
    "Robot with multi-functional work modules, suitable for multi-task operations.",
    "Equipped with multiple movable wheels, able to cross larger obstacles and perform tasks quickly.",
    "Robot that adapts to various terrains, able to easily handle different environments.",
    "Robot capable of walking steadily on sloped surfaces.",
    "Suitable for performing precise tasks in very small spaces.",
    "Robot equipped with complex path planning capabilities, capable of autonomous navigation and task completion.",
    "Highly flexible robotic arm, suitable for high-precision welding tasks.",
    "Robot capable of performing material handling tasks in complex environments through multiple degrees of freedom.",
    "Suitable for performing transportation and handling tasks in narrow passages.",
    "Robot with high load-bearing capacity, able to carry heavy objects.",
    "Extremely flexible robot, capable of performing complex assembly tasks.",
    "Robot arm capable of performing precision coating tasks.",
    "Robot with excellent terrain adaptability, capable of walking on steep slopes.",
    "Robot capable of performing cargo dismantling tasks.",
    "Precisely controlled robotic arm, suitable for electronic component assembly.",
    "Robot with self-balancing capability, able to cross obstacles and regain balance.",
    "Robot with off-road capabilities, able to overcome large terrain obstacles.",
    "Equipped with multifunctional operation arm, suitable for various complex tasks.",
    "Robot capable of autonomous navigation in complex terrain.",
    "Suitable for large-scale inspection tasks, equipped with autonomous patrolling capabilities.",
    "Highly integrated multifunctional robot, suitable for performing multiple tasks.",
    "Equipped with flexible operation modules, suitable for performing difficult tasks in confined spaces.",
    "Robotic arm suitable for complex assembly tasks in limited spaces.",
    "Robot that adapts to different ground types, capable of passing smoothly over various surfaces.",
    "Robot capable of quickly adjusting paths and positions, adapting to dynamic environmental changes.",
    "Robot with autonomous obstacle avoidance capability, able to efficiently avoid dynamic obstacles.",
    "Robot suitable for high-precision work environments, capable of performing complex precision assembly tasks.",
    "Equipped with leg-wheel hybrid system, capable of moving freely on both flat and uneven surfaces.",
    "Quadruped robot, adapts to various terrains through different gaits.",
    "Robot with powerful leg drive system, able to cross higher obstacles.",
    "Equipped with leg-wheel hybrid drive system, suitable for quick transitions between different terrains.",
    "Efficient quadruped robot, suitable for long-duration patrol tasks.",
    "Equipped with adjustable stride quadruped robot, suitable for different ground environments.",
    "Leg-wheel hybrid system robot, capable of handling complex terrains like sand and mud.",
    "Robot arm with collaboration capability, able to work in coordination with other robots or humans.",
    "Wheeled robot with fast turning capability, suitable for working in narrow spaces.",
    "Robot with integrated multifunctional tools, able to handle a variety of tasks.",
    "Robot adaptable to multiple operational modes, capable of switching between different working modes.",
    "High-precision robotic arm, suitable for handling small electronic components.",
    "Highly adaptive robot, able to automatically adjust working modes based on different ground types.",
    "Dual-arm collaborative robot, suitable for performing dual tasks.",
    "Robot suitable for high-intensity material handling tasks, with stronger load capacity.",
    "Robot suited for urban environments, able to cross sidewalks and low obstacles.",
    "Robot suitable for construction sites, capable of handling bulk cargo.",
    "Flexible robot, able to operate in a variety of environments.",
    "Four-wheel drive robot, suitable for navigation on complex city roads.",
    "High-speed moving robot, suitable for dense urban traffic areas.",
    "Robot with dynamic obstacle avoidance capability, suitable for high-speed operational environments.",
    "Robot adapted for special terrains, with powerful walking and climbing abilities.",
    "Robot with higher degrees of freedom, suitable for precision installation tasks.",
    "Robot suitable for long-distance transportation tasks.",
    "Automated warehouse robot, capable of efficient cargo handling.",
    "In a square room measuring 1000x1000, a robotic arm positioned at the center of the room is capable of extending its end effector to any of the four corners of the room.",
    "In an equilateral triangular room with each side measuring 500 units, a robotic arm positioned at one corner of the triangle is capable of extending its end effector to reach either of the other two corners of the room.",
    "A multi-wheeled robot capable of moving freely within a square room measuring 1000x1000."
]